apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sp-micro-service-argo-demo
  name: sp-micro-service-argo-demo
  namespace: dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sp-micro-service-argo-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sp-micro-service-argo-demo
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - sp-micro-service-argo-demo
            topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: install
        image: busybox:1.35.0
        args: [/bin/sh, -c, 'wget -O /app-configs/application.properties https://raw.githubusercontent.com/sinhasonalkumar/sp-micro-service-config-argo-demo/main/defaults/application.properties && wget -O /app-configs/application-dev.properties https://raw.githubusercontent.com/sinhasonalkumar/sp-micro-service-config-argo-demo/main/overrides/application-dev.properties']
        volumeMounts:
        - name: workdir
          mountPath: "/app-configs"
      containers:
      - image: sinhasonalkumar/sp-micro-service-argo-demo:1.0.0
        imagePullPolicy: Always
        name: sp-micro-service-argo-demo
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-Xms128m -Xmx512m"
        - name: "spring.config.location"
          value: "/app-configs/"
        - name: "spring.profiles.active"
          value: "dev"
        resources:
          requests:
            memory: 512Mi
          limits:
            memory: 512Mi
        volumeMounts:
        - name: workdir
          mountPath: "/app-configs"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: workdir
        emptyDir: {}