name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          path: ${GITHUB_WORKSPACE}
          VAR1: "Value of var1."
        env:
          ENV1: "Value Of environment variable env1."
      - name: Create Tag
        run: |
          git tag 0.0.1
          git checkout 0.0.1
      - name: BuildAndTest
        run: ./mvnw clean package
      - name: Container Build Tag And Push
        run: |
          docker build -t sp-micro-service-argo-demo .
          docker tag sp-micro-service-argo-demo sinhasonalkumar/sp-micro-service-argo-demo
          docker push sinhasonalkumar/sp-micro-service-argo-demo
      - name: Push Tag
        run: |
          git push origin 0.0.1

