name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          path: ${GITHUB_WORKSPACE}
          VAR1: "Value of var1."
        env:
          ENV1: "Value Of environment variable env1."
      - name : calculate-build-tag
        run : |
          export LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          if [[ -z "$LATEST_TAG" ]]
          then
            BUILD_TAG=1.0.0
          else
            BUILD_TAG=1.$(echo $BUILD_TAG | awk -F "." '{ printf $1+1 }').0
          fi
          echo "BUILD_TAG=$BUILD_TAG"
          echo "BUILD_TAG=$BUILD_TAG" >> $GITHUB_OUTPUT

      - name: create-tag
        run: |
          BUILD_TAG=${{ steps.build.outputs.BUILD_TAG }}
          echo "BUILD_TAG=$BUILD_TAG"
          git tag $BUILD_TAG
          git checkout $BUILD_TAG
      # - name: build-and-test
      #   run: ./mvnw clean package
      # - name: container-build-tag-and-push
      #   run: |
      #     BUILD_TAG=${{ steps.calculate-build-tag.outputs.BUILD_TAG }}
      #     echo $BUILD_TAG
      #     docker build -t sp-micro-service-argo-demo:$BUILD_TAG .
      #     docker tag sp-micro-service-argo-demo:$BUILD_TAG sinhasonalkumar/sp-micro-service-argo-demo:$BUILD_TAG
      #     docker push sinhasonalkumar/sp-micro-service-argo-demo
      # - name: Push Tag
      #   run: |
      #     BUILD_TAG=${{ steps.calculate-build-tag.outputs.BUILD_TAG }}
      #     echo $BUILD_TAG
      #     git push origin $BUILD_TAG

